Appbundle\Entity\RequestEntity\ProductDesignRequestEntity:
  ProductDesignRequest_{1..20}:
    name: <name()>
    email: <email()>
    company: <domainName()>
    contactNumber: <e164PhoneNumber()>
    message: <sentence()>
    type: <randomElement(['photo','video','design'])>
    quantity: <numberBetween(1,999)>
    postedAt: <dateTimeBetween('9 months', 'now')>
    isActive: <boolean(70)>